apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: mysql
type: Opaque
data:
  NAME: "MTIzNA=="
  USER: "dXNlcg=="
  PASSWORD: "MTIzNA=="
  HOST: "bXlzcWwtMC5teXNxbC5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbA=="